### PR TITLE
Fix clang compilation error. non-const lvalue ref cannot be bound to temporary

### PR DESCRIPTION
**Pull request by hplatou**
Fixes clang compiler error introduced by #1404.

```
rosbag2_py/src/rosbag2_py/_reader.cpp:48:37: error: non-const lvalue reference to type 'rosbag2_cpp::ConverterOptions' cannot bind to a temporary of type 'rosbag2_cpp::ConverterOptions'
    rosbag2_cpp::ConverterOptions & converter_options = rosbag2_cpp::ConverterOptions())
                                    ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

A non-const lvalue reference cannot be bound to a temporary.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

note: this is the only problem with humble.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21603/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15891/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1107/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22321/)

**Comment by hplatou** [comment]
> * Linux [Build Status](http://ci.ros2.org/job/ci_linux/21603/)
> * Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15891/)
> * Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1107/)
> * Windows [Build Status](http://ci.ros2.org/job/ci_windows/22321/)

These seems to be building against `rolling`

**Comment by clalancette** [comment]
New CI against Humble:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21621/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15908/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1125/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22338/)

**Comment by hplatou** [comment]
Any plans to release a 0.15.13 for Humble that will include this?

**Comment by fujitatomoya** [comment]
@audrow do we have any plan to `rosbag2_py` package upgrade for next release?
